accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout, password_change
from django.contrib import auth
from django.views.generic import TemplateView

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile/(?P<username>[a-zA-Z0-9_]{1,30})/$', views.profile,
        name='profile'),
    url(r'^edit/profile/$', views.editProfile, name='editProfile'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^change/password/$', password_change,
        {'template_name': 'accounts/change_password.html',
         'post_change_redirect': 'accounts:changePasswordDone'},
        name='changePassword'),
    url(r'^change/password/done/$',
        TemplateView.as_view(
            template_name='accounts/change_password_done.html'),
        name='changePasswordDone'),
]

it/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views import static
# from django.conf import settings
from . import settings

urlpatterns = i18n_patterns(
    url(r'^', include('core.urls')),
    url(r'^ajax/', include('ajax.urls')),
    url(r'ajax/chat/', include('chat.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('it._urls')),
)

urlpatterns += [url(r'^', include('fakeadmin.urls')), ]
if settings.DEBUG:
    urlpatterns += i18n_patterns(
        url(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT
        })
    )

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    middle_name = models.CharField(max_length=50, blank=True)

    def get_avatar_filename(instance, filename):
        return 'avatars/user_{0}/{1}'.format(instance.user.id, filename)
    avatar = models.ImageField(upload_to=get_avatar_filename,
                               null=True, blank=True)

    def __str__(self):
        return self.user.username if self.user is not None else "anon"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.files.images import get_image_dimensions
from .models import Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    middle_name = forms.CharField(required=False)
    avatar = forms.ImageField(required=False)

    class Meta:
        model = Profile
        fields = ('middle_name', 'avatar')

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']

        try:
            width, height = get_image_dimensions(avatar)

            max_width = max_height = 500
            if width > max_width or height > max_height:
                raise forms.ValidationError(
                    'Слишком много пикселей. '
                    'Надо не больше %sx%s' % (max_width, max_height)
                )

            print(avatar.__dict__)
            main, sub = avatar.content_type.split('/')
            avatar._name = 'avatar.' + sub
            if not (main == 'image' and sub in ['jpeg', 'jpg', 'gif', 'png']):
                raise forms.ValidationError(
                    'Разрешённые файлы: .jpeg, .jpg, .png, .gif')

            if len(avatar) > (10 * 1024):
                raise forms.ValidationError(
                    'Слишком много байтов')

        except AttributeError:
            """
            Handles case when we are updating the user profile
            and do not supply a new avatar
            """
            pass

        return avatar

accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.db import transaction
from .forms import UserForm, ProfileForm
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from core.views import Event


def index(request):
    return render(request, 'accounts/index.html')


def profile(request, username):
    # user = User.objects.get(username=username)
    user = get_object_or_404(User, username=username)
    events = Event.objects.filter(owner=user)

    paginator = Paginator(events, 10)
    page = request.GET.get('page')
    try:
        events_list = paginator.page(page)
    except PageNotAnInteger:
        events_list = paginator.page(1)
    except EmptyPage:
        events_list = paginator.page(paginator.num_pages)

    events_list.paginator.low_bound = events_list.number - 5
    events_list.paginator.middle_bound = events_list.number + 5
    events_list.paginator.high_bound = events_list.paginator.num_pages - 2

    return render(request, 'accounts/profile.html', {
        'user': user,
        'events': events_list,
    })


@transaction.atomic
@login_required
def editProfile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES,
                                   instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(
                reverse('accounts:profile',
                        kwargs={'username': request.user.username}))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        if username == 'admin' or username == 'moderator' or \
           username == 'administrator':
            return redirect(reverse('fakeAdmin:fakeAdmin'))

    return auth.views.login(request, template_name='accounts/login.html')


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('core.index'))

templates/accounts/change_password.html
{% extends 'core/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}IT microphone{% endblock %}

{% block head %}

{% endblock %}

{% block content %}
<form action="." method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="{% trans 'Сохранить' %}">
</form>
{% endblock %}

templates/accounts/change_password_done.html
{% extends 'core/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}IT microphone{% endblock %}

{% block head %}

{% endblock %}

{% block content %}
<p>
Пароль успешно изменён. 
</p>
{% endblock %}

templates/accounts/edit_profile.html
{% extends 'core/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}IT microphone{% endblock %}

{% block head %}

{% endblock %}

{% block content %}
<div class="form_wrapper edit_profile_form_wrapper">
	<form id="edit_profile_form" action="." enctype="multipart/form-data" method="post">
		{% csrf_token %}
		{{ user_form.as_p }}
		{{ profile_form.as_p }}
		<input type="submit" value="{% trans 'Сохранить' %}">
	</form>
<a href="{% url 'accounts:changePassword' %}">{% trans 'Изменить пароль' %}</a>
</div>
{% endblock %}

templates/accounts/login.html
{% extends 'core/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}IT microphone{% endblock %}

{% block head %}

{% endblock %}

{% block content %}
<div class="form_wrapper">
	<form action="." method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="{% trans 'Войти' %}">
	</form>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends 'core/base.html' %}

{% load static %}
{% load i18n %}


{% block title %}IT microphone{% endblock %}

{% block head %}

{% endblock %}

{% block content %}
	<h2>{{ user.username }}</h2>
<div class="user_profile">
	{% if user.profile.avatar and user.profile.avatar.url is not None %}
	<div class="avatar">
		<img src="{{ user.profile.avatar.url }}">
	</div>
	{% endif %}
	<div class="options">
		{% if user.last_name|length != 0 or user.first_name|length != 0 or user.profile.middle_name|length != 0 %}
		<div class="option">
			<div class="key">{% if user.last_name|length != 0 %}Фамилия{% endif %} {% if user.first_name|length != 0 %}Имя{% endif %} {% if user.profile.middle_name|length != 0 %}Отчество{% endif %}</div>
			<div class="value">{{ user.last_name }} {{ user.first_name }} {{ user.profile.middle_name }}</div>
		</div>	
		{% endif %}
	</div>
</div>
<h2>Список событий</h2>
{% include 'core/parts/events.part.html' %}

{% endblock %}