accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout, password_change
from django.contrib import auth
from django.views.generic import TemplateView

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile/(?P<username>[a-zA-Z0-9_]{1,30})/$', views.profile,
        name='profile'),
    url(r'^edit/profile/$', views.editProfile, name='editProfile'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^change/password/$', password_change,
        {'template_name': 'accounts/change_password.html',
         'post_change_redirect': 'accounts:changePasswordDone'},
        name='changePassword'),
    url(r'^change/password/done/$',
        TemplateView.as_view(
            template_name='accounts/change_password_done.html'),
        name='changePasswordDone'),
]

chat/urls.py
from django.conf.urls import url
from . import views


app_name = 'chat'
urlpatterns = [
    url(r'^(?P<pk>[0-9]{1,10})/messages/$', views.getMessages,
        name='getMessages'),
    url(r'^message/(?P<pk>[0-9]{1,10})/vote/(?P<action>[0-9])/$',
        views.messageVote, name='messageVote'),
    url(r'^(?P<pk>[0-9]{1,10})/add/message/$', views.addMessage,
        name='addMessage'),
#    url(r'^$', views.eventListView, {'category': 'future'}, name='index'),
#    url(r'^event/(?P<pk>[0-9]{1,10})/$', views.eventDetail,
#        name='event_detail'),
]

core/urls.py
from django.conf.urls import url

from . import views


app_name = 'core'
urlpatterns = [
    url(r'^$', views.eventListView, {'category': 'future'}, name='index'),
    url(r'^events/(?P<category>[a-z]{1,10})/$',
        views.eventListView, name='eventList'),
    # url(r'^event/(?P<pk>[0-9]{1,10})/$', views.EventDetailView.as_view(),
    #    name='event_detail')
    url(r'^event/(?P<pk>[0-9]{1,10})/$', views.eventDetail,
        name='event_detail'),
    url(r'^add/event/', views.addEvent, name='addEvent'),
    url(r'^edit/event/(?P<pk>[0-9]{1,10})/$', views.editEvent,
        name='editEvent'),
]

it/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views import static
# from django.conf import settings
from . import settings

urlpatterns = i18n_patterns(
    url(r'^', include('core.urls')),
    url(r'^ajax/', include('ajax.urls')),
    url(r'ajax/chat/', include('chat.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('it._urls')),
)

urlpatterns += [url(r'^', include('fakeadmin.urls')), ]
if settings.DEBUG:
    urlpatterns += i18n_patterns(
        url(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT
        })
    )

core/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from chat.models import Chat


class Event(models.Model):
    owner = models.ForeignKey(User, related_name='owner',
                              on_delete=models.SET_NULL, null=True)
#    lectors = models.ManyToManyField(User
    theme = models.CharField(max_length=150)
    description = models.CharField(max_length=1500)
    location = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    event_start_time = models.DateTimeField()
    event_end_time = models.DateTimeField()
    need_subscribers = models.IntegerField()
    subscribers = models.ManyToManyField(User)

    chat = models.OneToOneField(Chat, on_delete=models.CASCADE)

    def __str__(self):
        return self.theme

    def save(self, *args, **kwargs):
        if not (hasattr(self, 'chat') and self.chat is not None):
            self.chat = Chat.objects.create()
        if self.need_subscribers < 0:
            raise ValueError("")
        if self.event_start_time >= self.event_end_time:
            raise ValueError(
                "Дата начала не может быть больше или равна дате конца события")
        super(Event, self).save(*args, **kwargs)

    def wasPublishedRecently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def expired(self):
        return self.event_end_time < timezone.now()

    def duration(self):
        return self.event_end_time - self.event_start_time

    class Meta:
        ordering = ['pub_date']

core/forms.py
from django.forms import ModelForm, Textarea
from django import forms
from .models import Event


class EventForm(ModelForm):
    def clean(self):
        # cleaned_data =
        super(EventForm, self).clean()
        event_start_time = self.cleaned_data['event_start_time']
        event_end_time = self.cleaned_data['event_end_time']
        if event_start_time >= event_end_time:
            raise forms.ValidationError(
                "Дата начала не может быть больше или равна дате конца события")

    def save(self, commit=True):

        return super(EventForm, self).save(commit=commit)

    class Meta:
        model = Event
        fields = ('theme', 'description', 'location', 'event_start_time',
                  'event_end_time', 'need_subscribers')
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 20}),
            'event_start_time': forms.DateTimeInput(
                attrs={'class': 'datepicker timepicker'},
                format='%Y-%m-%d %H:%M'),
            'event_end_time': forms.DateTimeInput(
                attrs={'class': 'datepicker timepicker'},
                format='%Y-%m-%d %H:%M')
        }


class EventAddForm(EventForm):
    class Meta(EventForm.Meta):
        model = Event
        fields = ('theme', 'description', 'location', 'event_start_time',
                  'event_end_time', 'need_subscribers')


class EventEditForm(EventForm):
    class Meta(EventForm.Meta):
        model = Event
        # fields = ('theme', 'description', 'location', 'event_end_time',
        #          'need_subscribers'),
        widgets = {
            'theme': forms.TextInput(attrs={'readonly': 'readonly'}),
            'description': Textarea(attrs={'cols': 80, 'rows': 20}),
            'event_start_time': forms.DateTimeInput(
                attrs={'readonly': 'readonly'},
                format='%Y-%m-%d %H:%M'),
            'event_end_time': forms.DateTimeInput(
                attrs={'class': 'datepicker timepicker'},
                format='%Y-%m-%d %H:%M')
        }

core/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db import transaction
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Event
from .forms import EventAddForm, EventEditForm
from chat.forms import ChatMessageAddForm
from chat.models import ChatMessage


def index(request):
    events = Event.objects.all().order_by('-event_start_time')

    subscribers = []
    for event in events:
        event.subscribed = False

    return render(request, 'core/index.html', {
        'events': events,
        'subscribers': subscribers
    })


def eventListView(request, category):
    if category == 'past':
        events = Event.objects.filter(event_end_time__lte=timezone.now())
    elif category == 'future':
        events = Event.objects.filter(event_start_time__gte=timezone.now())
    elif category == 'my':
        if not request.user.is_authenticated():
            raise Http404()
        events = Event.objects.filter(owner=request.user)
    else:
        events = Event.objects.all().order_by('-event_start_time')

    paginator = Paginator(events, 10)
    page = request.GET.get('page')
    try:
        events_list = paginator.page(page)
    except PageNotAnInteger:
        events_list = paginator.page(1)
    except EmptyPage:
        events_list = paginator.page(paginator.num_pages)

    events_list.paginator.low_bound = events_list.number - 5
    events_list.paginator.middle_bound = events_list.number + 5
    events_list.paginator.high_bound = events_list.paginator.num_pages - 2
    return render(request, 'core/events_list.html', {
        'category': category,
        'events': events_list,
    })


def eventDetail(request, pk=None):
    event = get_object_or_404(Event, pk=pk)
    event.subscribed = True
    form = ChatMessageAddForm()
    chatMessages = \
        ChatMessage.objects.filter(chat=event.chat).order_by('pk')[:10]

    return render(request, 'core/event_detail.html', {
        'event': event,
        'form': form,
        'chatMessages': chatMessages,
    })


@transaction.atomic
@login_required
def addEvent(request):
    if request.method == 'POST':
        form = EventAddForm(request.POST)

        if form.is_valid():
            event = form.save(commit=False)

            event.owner = request.user
            event.save()

            return HttpResponseRedirect(
                reverse('accounts:profile',
                        kwargs={'username': request.user.username}))
    else:
        form = EventAddForm()

    return render(request, 'core/add_event.html', {'form': form})


@transaction.atomic
@login_required
def editEvent(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.user != event.owner:
        raise Http404()

    if request.method == 'POST':
        form = EventEditForm(request.POST)

        if form.is_valid():
            result = form.cleaned_data
            event.description = result['description']
            event.location = result['location']
            event.event_end_time = result['event_end_time']
            event.need_subscribers = result['need_subscribers']
            event.save()

            return HttpResponseRedirect(reverse('core:event_detail',
                                        kwargs={'pk': event.pk}))
    else:
        form = EventEditForm(initial={
            'theme': event.theme,
            'description': event.description,
            'location': event.location,
            'event_start_time': event.event_start_time,
            'event_end_time': event.event_end_time,
            'need_subscribers': event.need_subscribers,
        })

    return render(request, 'core/edit_event.html', {'form': form})

templates/core/add_event.html
{% extends 'core/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}IT microphone{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'core/css/timepicker-ui.min.css' %}" type="text/css"/> 
<script src="{% static 'core/js/timepicker-ui.min.js' %}"></script>
{% endblock %}

{% block content %}
<h2>Добавить событие</h2>
<div class="form_wrapper">
	<form action="." method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="{% trans 'Добавить' %}">
	</form>
</div>
<script>
$(".datepicker").datepicker({dateFormat: 'yy-mm-dd T'});
$('.timepicker').timePicker();
</script>
{% endblock %}

templates/core/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{% if language %}{{ language }}{% else %}ru{% endif %}">
<head>
	<title>{% block title %}title{% endblock %}</title>
	<meta charset="utf-8">
	<!-- <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}"> -->
	<!-- <link rel="stylesheet" href="{% static 'core/css/bootstrap-theme.css' %}"> -->
	<link rel="stylesheet" href="{% static 'core/css/base.css' %}" >
	<link rel="stylesheet" href="{% static 'core/css/style.css' %}" >

	<script src="{% static 'core/js/jquery.js' %}"></script>

	<link type="text/css" href="{% static 'core/css/jquery-ui.min.css' %}" rel="stylesheet" />
	<link type="text/css" href="{% static 'core/css/jquery-ui.theme.min.css' %}" rel="stylesheet" />
	<link rel="stylesheet" href="{% static 'core/css/event_detail.css' %}" >
	<script type="text/javascript" src="{% static 'core/js/jquery-ui.min.js' %}"></script>
	<script src="{% static 'core/js/dom_generator.js' %}" charset="utf-8"></script>
	<script src="{% static 'core/js/core.js' %}" charset="utf-8"></script>
	<script src="{% static 'core/js/urls.js' %}" charset="utf-8"></script>
	<script src="{% static 'core/js/events.js' %}" charset="utf-8"></script>
	<script src="{% static 'core/js/chat.js' %}" charset="utf-8"></script>

	<script>
		function getCookie(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = jQuery.trim(cookies[i]);
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getCookie('csrftoken');

		function csrfSafeMethod(method) {
		    // these HTTP methods do not require CSRF protection
		    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}
		$.ajaxSetup({
		    beforeSend: function(xhr, settings) {
		        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
		            xhr.setRequestHeader("X-CSRFToken", csrftoken);
		        }
		    }
		});
	</script>
	{% block head %}{% endblock %}
</head>
<body>
<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter43414749 = new Ya.Metrika({ id:43414749, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/43414749" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->

	<div id="content">
	<div id="beta">beta version</div>
	<div id="ajaxResult"></div>
	<div class="sidebar">
	{% if request.user.is_authenticated %}
		
			<div class="item profile-button">
				<a href="{% url 'accounts:profile' username=request.user.username %}">{{ request.user.username }}</a>
			</div>
			<div class="item edit-profile-button">
				<a href="{% url 'accounts:editProfile' %}">Редактировать профиль</a>
			</div>
		<div class="item add-event-button">
			<a href="{% url 'core:addEvent' %}">Добавить событие</a>
		</div>
		{% else %}
		<div class="login-button">
			<a href="{% url 'accounts:login' %}">Войти</a>
		</div>
		{% endif %}

		<div class="item">
			<div class="hide_show_button">&gt;</div>
			<a href="{% url 'core:index' %}">События</a>
			<div class="submenu">
				<div class="subitem">
					<a href="{% url 'core:eventList' category='future' %}">Предстоящие</a>
				</div>
				<div class="subitem">
					<a href="{% url 'core:eventList' category='past' %}">Прошедшие</a>
				</div>
				{% if request.user.is_authenticated %}
				<div class="subitem">
					<a href="{% url 'core:eventList' category='my' %}">Мои</a>
				</div>
				{% endif %}
			</div>
		</div>
		<!-- 
		<div class="item">
			<div class="hide_show_button">&gt;</div>
			<a href="{% url 'core:index' %}">Обсуждения</a>
			<div class="submenu">
				<div class="subitem">
				<a href="{% url 'core:eventList' category='future' %}">Интересные</a>
				</div>
				<div class="subitem">
					<a href="{% url 'core:eventList' category='past' %}">Новые</a>
				</div>
				{% if request.user.is_authenticated %}
				<div class="subitem">
					<a href="{% url 'core:eventList' category='my' %}">Мои</a>
				</div>
				{% endif %}
			</div>
		</div>
		-->

		{% if request.user.is_authenticated %}
			<div class="item logout-button">
				<a href="{% url 'accounts:logout' %}">Выйти</a>
			</div>
		{% endif %}
	</div>
	<script>
	/* sidebar items */
	make_sidebar_menu();
	</script>
	<div class="posts">
	{% block header %}
	{% endblock %}
{% block content %}{% endblock %}
	</div>
	</div>

	<script src="{% static 'core/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/core/edit_event.html
{% extends 'core/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}IT microphone{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'core/css/timepicker-ui.min.css' %}" type="text/css"/> 
<script src="{% static 'core/js/timepicker-ui.min.js' %}"></script>
{% endblock %}

{% block content %}
<h2>Редактировать событие</h2>
<div class="form_wrapper">
	<form action="." method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="{% trans 'Добавить' %}">
	</form>
</div>
<script>
$(".datepicker").datepicker({dateFormat: 'yy-mm-dd T'});
$('.timepicker').timePicker();
</script>
{% endblock %}

templates/core/event_detail.html
{% load is_user_subscribed_to_event %}
{% load mathfilters %}
{% load i18n %}

<div id="event_detail_frame">
	<div class="header">
		<h1 class="theme">{{ event.theme }}</h1>
		<div class="button-wrapper">
			<button class="{% if user|is_user_subscribed_to_event:event %}subscribed-button{% else %}subscribe-button{% endif %}" onclick="{% if user|is_user_subscribed_to_event:event %}unsubscribeFromEvent(this, {{ event.pk }}){% else %}subscribeToEvent(this, {{ event.pk }}){% endif %}" subscribers="{{ event.subscribers.count }}">{% if user|is_user_subscribed_to_event:event %}Отписаться{% else %}Подписаться{% endif %} ({{ event.subscribers.count }})</button>
		</div>
	</div>
	<div id="content">
		<!-- <div class="lector"> -->
				{% if event.owner.profile.avatar and event.owner.profile.avatar.url is not None %}
				<div class="avatar">
					<img src="{{ event.owner.profile.avatar.url }}">
				</div>
				{% endif %}
		<!-- </div> -->
		<div class="options">
			<div class="option">
				<div class="key">Лектор</div>
				<div class="value">{{ event.owner.username }}</div>
			</div>
			<div class="option">
				<div class="key">Место проведения</div>
				<div class="value">{{ event.location }}</div>
			</div>
			<div class="option">
				<div class="key">Дата и время начала</div>
				<div class="value">{{ event.event_start_time }}</div>
			</div>
			<div class="option">
				<div class="key">Длительность</div>
				<div class="value">{{ event.duration }}</div>
			</div>
			<div class="option">
				<div class="key">Необходимо подписчиков</div>
				<div class="value">{{ event.need_subscribers }}</div>
			</div>
		</div>
		<div class="description">
		{{ event.description }}
		</div>
		<div id="eventChat" class="chat">
			<div class="comments_count">{% trans 'Количество комментариев' %} - {{ event.chat.count_messages }}</div>
			<div class="messages">

			</div>
			<script>updateChat(eventChat, {{ event.chat.pk }}, 0, 50);</script>
			<a class="update_button" href="#" onclick="updateChat(eventChat, {{ event.chat.pk }}, 0, 50)">Обновить</a>
		</div>
		<form id="add_comment_form" action="." method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="{% trans 'Отправить' %}">
		</form>
		<script>
		$('#add_comment_form').on('submit', function(event){
		    event.preventDefault();
		    addComment($(this).serialize());
		});
		</script>

		<script>
		function addComment(formData) {
			$.ajax({
				type: 'POST',
				url: '{% url 'chat:addMessage' pk=event.chat.pk %}',
				data: formData,
				success: function(data) {
					showNotification(data.text);
					if(!data.state)
						return;
					updateChat(eventChat, {{ event.chat.pk }}, 0, 50);
					$('#add_comment_form ').find("input[type=text], textarea").val("");
				},
				error: function(xhr, str) {
					alert('Возникла ошибка: ' + xhr.responseCode);
				}
			});
		}

		var n = 0
		
		</script>
	</div>
</div>

templates/core/events_list.html
{% extends 'core/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}IT microphone{% endblock %}

{% block content %}
<h2 class="events-header">
{% if category == 'past' %}
{% trans "Прошедшие события" %}
{% elif category == 'future' %}
{% trans "Предстоящие события" %}
{% endif %}
</h2>
{% include 'core/parts/events.part.html' %}


{% endblock %}

templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}IT microphone{% endblock %}

{% block content %}
index



{% endblock %}

templates/core/test.html
<h1>test</h1>

{{ user }}
<br>
<br>
{{ voted }}