accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout, password_change
from django.contrib import auth
from django.views.generic import TemplateView

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile/(?P<username>[a-zA-Z0-9_]{1,30})/$', views.profile,
        name='profile'),
    url(r'^edit/profile/$', views.editProfile, name='editProfile'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^change/password/$', password_change,
        {'template_name': 'accounts/change_password.html',
         'post_change_redirect': 'accounts:changePasswordDone'},
        name='changePassword'),
    url(r'^change/password/done/$',
        TemplateView.as_view(
            template_name='accounts/change_password_done.html'),
        name='changePasswordDone'),
]

core/urls.py
from django.conf.urls import url

from . import views


app_name = 'core'
urlpatterns = [
    url(r'^$', views.eventListView, {'category': 'future'}, name='index'),
    url(r'^events/(?P<category>[a-z]{1,10})/$',
        views.eventListView, name='eventList'),
    # url(r'^event/(?P<pk>[0-9]{1,10})/$', views.EventDetailView.as_view(),
    #    name='event_detail')
    url(r'^event/(?P<pk>[0-9]{1,10})/$', views.eventDetail,
        name='event_detail'),
    url(r'^add/event/', views.addEvent, name='addEvent'),
    url(r'^edit/event/(?P<pk>[0-9]{1,10})/$', views.editEvent,
        name='editEvent'),
]

it/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views import static
# from django.conf import settings
from . import settings

urlpatterns = i18n_patterns(
    url(r'^', include('core.urls')),
    url(r'^ajax/', include('ajax.urls')),
    url(r'ajax/chat/', include('chat.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('it._urls')),
)

urlpatterns += [url(r'^', include('fakeadmin.urls')), ]
if settings.DEBUG:
    urlpatterns += i18n_patterns(
        url(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT
        })
    )

core/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from chat.models import Chat


class Event(models.Model):
    owner = models.ForeignKey(User, related_name='owner',
                              on_delete=models.SET_NULL, null=True)
#    lectors = models.ManyToManyField(User
    theme = models.CharField(max_length=150)
    description = models.CharField(max_length=1500)
    location = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    event_start_time = models.DateTimeField()
    event_end_time = models.DateTimeField()
    need_subscribers = models.IntegerField()
    subscribers = models.ManyToManyField(User)

    chat = models.OneToOneField(Chat, on_delete=models.CASCADE)

    def __str__(self):
        return self.theme

    def save(self, *args, **kwargs):
        if not (hasattr(self, 'chat') and self.chat is not None):
            self.chat = Chat.objects.create()
        if self.need_subscribers < 0:
            raise ValueError("")
        if self.event_start_time >= self.event_end_time:
            raise ValueError(
                "Дата начала не может быть больше или равна дате конца события")
        super(Event, self).save(*args, **kwargs)

    def wasPublishedRecently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def expired(self):
        return self.event_end_time < timezone.now()

    def duration(self):
        return self.event_end_time - self.event_start_time

    class Meta:
        ordering = ['pub_date']

core/forms.py
from django.forms import ModelForm, Textarea
from django import forms
from .models import Event


class EventForm(ModelForm):
    def clean(self):
        # cleaned_data =
        super(EventForm, self).clean()
        event_start_time = self.cleaned_data['event_start_time']
        event_end_time = self.cleaned_data['event_end_time']
        if event_start_time >= event_end_time:
            raise forms.ValidationError(
                "Дата начала не может быть больше или равна дате конца события")

    def save(self, commit=True):

        return super(EventForm, self).save(commit=commit)

    class Meta:
        model = Event
        fields = ('theme', 'description', 'location', 'event_start_time',
                  'event_end_time', 'need_subscribers')
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 20}),
            'event_start_time': forms.DateTimeInput(
                attrs={'class': 'datepicker timepicker'},
                format='%Y-%m-%d %H:%M'),
            'event_end_time': forms.DateTimeInput(
                attrs={'class': 'datepicker timepicker'},
                format='%Y-%m-%d %H:%M')
        }


class EventAddForm(EventForm):
    class Meta(EventForm.Meta):
        model = Event
        fields = ('theme', 'description', 'location', 'event_start_time',
                  'event_end_time', 'need_subscribers')


class EventEditForm(EventForm):
    class Meta(EventForm.Meta):
        model = Event
        # fields = ('theme', 'description', 'location', 'event_end_time',
        #          'need_subscribers'),
        widgets = {
            'theme': forms.TextInput(attrs={'readonly': 'readonly'}),
            'description': Textarea(attrs={'cols': 80, 'rows': 20}),
            'event_start_time': forms.DateTimeInput(
                attrs={'readonly': 'readonly'},
                format='%Y-%m-%d %H:%M'),
            'event_end_time': forms.DateTimeInput(
                attrs={'class': 'datepicker timepicker'},
                format='%Y-%m-%d %H:%M')
        }

core/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db import transaction
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Event
from .forms import EventAddForm, EventEditForm
from chat.forms import ChatMessageAddForm
from chat.models import ChatMessage


def index(request):
    events = Event.objects.all().order_by('-event_start_time')

    subscribers = []
    for event in events:
        event.subscribed = False

    return render(request, 'core/index.html', {
        'events': events,
        'subscribers': subscribers
    })


def eventListView(request, category):
    if category == 'past':
        events = Event.objects.filter(event_end_time__lte=timezone.now())
    elif category == 'future':
        events = Event.objects.filter(event_start_time__gte=timezone.now())
    elif category == 'my':
        if not request.user.is_authenticated():
            raise Http404()
        events = Event.objects.filter(owner=request.user)
    else:
        events = Event.objects.all().order_by('-event_start_time')

    paginator = Paginator(events, 10)
    page = request.GET.get('page')
    try:
        events_list = paginator.page(page)
    except PageNotAnInteger:
        events_list = paginator.page(1)
    except EmptyPage:
        events_list = paginator.page(paginator.num_pages)

    events_list.paginator.low_bound = events_list.number - 5
    events_list.paginator.middle_bound = events_list.number + 5
    events_list.paginator.high_bound = events_list.paginator.num_pages - 2
    return render(request, 'core/events_list.html', {
        'category': category,
        'events': events_list,
    })


def eventDetail(request, pk=None):
    event = get_object_or_404(Event, pk=pk)
    event.subscribed = True
    form = ChatMessageAddForm()
    chatMessages = \
        ChatMessage.objects.filter(chat=event.chat).order_by('pk')[:10]

    return render(request, 'core/event_detail.html', {
        'event': event,
        'form': form,
        'chatMessages': chatMessages,
    })


@transaction.atomic
@login_required
def addEvent(request):
    if request.method == 'POST':
        form = EventAddForm(request.POST)

        if form.is_valid():
            event = form.save(commit=False)

            event.owner = request.user
            event.save()

            return HttpResponseRedirect(
                reverse('accounts:profile',
                        kwargs={'username': request.user.username}))
    else:
        form = EventAddForm()

    return render(request, 'core/add_event.html', {'form': form})


@transaction.atomic
@login_required
def editEvent(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.user != event.owner:
        raise Http404()

    if request.method == 'POST':
        form = EventEditForm(request.POST)

        if form.is_valid():
            result = form.cleaned_data
            event.description = result['description']
            event.location = result['location']
            event.event_end_time = result['event_end_time']
            event.need_subscribers = result['need_subscribers']
            event.save()

            return HttpResponseRedirect(reverse('core:event_detail',
                                        kwargs={'pk': event.pk}))
    else:
        form = EventEditForm(initial={
            'theme': event.theme,
            'description': event.description,
            'location': event.location,
            'event_start_time': event.event_start_time,
            'event_end_time': event.event_end_time,
            'need_subscribers': event.need_subscribers,
        })

    return render(request, 'core/edit_event.html', {'form': form})

templates/core/parts/events.part.html
{% load static %}
{% load i18n %}
{% load is_user_subscribed_to_event %}

{% if events.has_other_pages %}
<div class="pagination-wrapper">
    <div class="pagination">
        <span class="step-links">
            {% if events.has_previous %}
                <a class="button prev" href="?page={{ events.previous_page_number }}">&lt;</a>
            {% endif %}
            {% for page_number in events.paginator.page_range %}
            	{% if forloop.counter == 1 or forloop.counter > events.paginator.low_bound and forloop.counter < events.paginator.middle_bound or forloop.counter > events.paginator.high_bound %}
                <a class="button page{% if page_number == events.number %} active_page{% endif %}" href="?page={{ page_number }}">{{ page_number }}</a>
                <!-- {{forloop.counter}} -->
                {% else %}
                	{% if forloop.counter == events.paginator.middle_bound or forloop.counter == events.paginator.low_bound %}
                	...
                	{% endif %}
                {% endif %}
            {% endfor %}
            {% if events.has_next %}
                <a class="button next" href="?page={{ events.next_page_number }}">&gt;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endif %}
<div class="events-row">
	{% for event in events %}
		<div id="eventN{{ event.pk }}" class="event">
			<div class="header">
				<div class="theme">{{ event.theme }}</div>
				{% if request.user == event.owner %}
				<div class="edit"><a href="{% url 'core:editEvent' pk=event.pk %}">Редактировать</a></div>
				{% endif %}
			</div>
			<div class="wrapper">
				<div class="options">
					<div class="option">
						<div class="key">Автор</div>
						<div class="value"><a href="{% url 'accounts:profile' username=event.owner.username %}">{{ event.owner.username }}</a></div>
					</div>
					<div class="option">
						<div class="key">Место проведения</div>
						<div class="value">{{ event.location }}</div>
					</div>
					<div class="option">
						<div class="key">Дата и время начала</div>
						<div class="value">{{ event.event_start_time }}</div>
					</div>
					<div class="option">
						<div class="key">Длительность</div>
						<div class="value">{{ event.duration }}</div>
					</div>
					<div class="option">
						<div class="key">Необходимо подписчиков</div>
						<div class="value">{{ event.need_subscribers }}</div>
					</div>
				</div>

				<div class="description">
				{{ event.description }}
				{{ event.subscribed }}
				</div>
			</div>
			<div class="buttons">
				<button class="more-button" onclick="showEventPopup({{ event.pk }})">Подробнее</button>
				<button class="{% if user|is_user_subscribed_to_event:event %}subscribed-button{% else %}subscribe-button{% endif %}" onclick="{% if user|is_user_subscribed_to_event:event %}unsubscribeFromEvent(this, {{ event.pk }}){% else %}subscribeToEvent(this, {{ event.pk }}){% endif %}" subscribers="{{ event.subscribers.count }}">{% if user|is_user_subscribed_to_event:event %}Отписаться{% else %}Подписаться{% endif %} ({{ event.subscribers.count }})</button>
			</div>
		</div>
	{% empty %}
	<h3>На складе ничего не найдено</h3>
	{% endfor %}
</div>
{% if events.has_other_pages %}
<div class="pagination-wrapper">
    <div class="pagination">
        <span class="step-links">
            {% if events.has_previous %}
                <a class="button prev" href="?page={{ events.previous_page_number }}">&lt;</a>
            {% endif %}
            {% for page_number in events.paginator.page_range %}
            	{% if forloop.counter == 1 or forloop.counter > events.paginator.low_bound and forloop.counter < events.paginator.middle_bound or forloop.counter > events.paginator.high_bound %}
                <a class="button page{% if page_number == events.number %} active_page{% endif %}" href="?page={{ page_number }}">{{ page_number }}</a>
                <!-- {{forloop.counter}} -->
                {% else %}
                	{% if forloop.counter == events.paginator.middle_bound or forloop.counter == events.paginator.low_bound %}
                	...
                	{% endif %}
                {% endif %}
            {% endfor %}
            {% if events.has_next %}
                <a class="button next" href="?page={{ events.next_page_number }}">&gt;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endif %}
<div id="event_popup" class="anim_event_popup_showing"  style="display: none;">
	<div class="close-button">X</div>
	<div id="event_popup_frame" class="anim_event_popup_frame_showing" onclick="function() { return false; }">

	</div>
	<!-- <iframe id="event_popup_frame" class="anim_event_popup_frame_showing"  src=""  frameborder="no" seamless>
	{% blocktrans %}У вас плохой браузер :({% endblocktrans %}
	</iframe> -->
</div>

<script>
$('#event_popup').click(function(event) {
	hideEventPopup();
})
$('#event_popup #event_popup_frame').click(function(event) {
	event.stopPropagation();
})
</script>